spring.application.name=ragapi
spring.datasource.url=jdbc:postgresql://localhost:5432/smartdocs
spring.datasource.username=postgres
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.ai.openai.api-key=${OPENAI_API_KEY}
server.port=8081
