spring.application.name=ragapi
spring.datasource.url=jdbc:postgresql://localhost:5432/smartdocs
spring.datasource.username=postgres
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.ai.openai.api-key=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
server.port=8081
